### ISSUE TITLE
Assignment solutions missing

### ISSUE THREAD

**Issue by m4nuC** [stanford-cs221/autumn2019#18]
On the course website, they are listed under the `assignments` directory, eg. https://stanford-cs221.github.io/autumn2019/assignments/foundations-solutions.zip, however, they seem to be missing. 
Is it possible to find them somewhere else? 

Thanks a lot

**Comment by rpryzant** [comment]
Solutions were only made available to enrolled students. Sorry!

**Comment by LavenderMP** [comment]
@rpryzant since the new course is coming, there are any chance to publish the solution from last quarter?

**Comment by rpryzant** [comment]
No, sorry!
